name: Build OpenAPI Lago Client

on:
  push:
    branches:
      - 'v*.*.*'
  pull_request:
    branches:
      - 'v*.*.*'

jobs:
  generate-php-client:
    runs-on: ubuntu-latest
    name: Generate OpenAPI PHP Client
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Generate Lago PHP Client
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: php
          openapi-url: https://raw.githubusercontent.com/getlago/lago-openapi/a4bee71b26f6b00fe19d93ab91ee1180af6d934d/openapi.yaml
          command-args: "--additional-properties=invokerPackage=Lago\\Client -o . --skip-validate-spec"
          
      - name: Auto-Heal composer.json
        uses: sergeysova/jq-action@v2
        with:
          cmd: |
            jq ".name = \"$(echo ${GITHUB_REPOSITORY} | tr '[:upper:]' '[:lower:]')\"" composer.json > composer.json.tmp
            mv composer.json.tmp composer.json
          
      - name: "Install dependencies"
        uses: php-actions/composer@v6
        
      - name: Run tests
        run: vendor/bin/phpunit
      
      - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          fetch: false
          message: "Update Lago PHP CLient ${{github.ref_name}}"
          tag: "${{github.ref_name}} --force"
          tag_push: '--force'
